<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>forgot_back</name>
   <tag></tag>
   <elementGuidId>e6c38340-80c3-4325-a8e7-0c646bf5b2a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'page-signin-forgot-back' and (text() = '← Kembali' or . = '← Kembali') and @href = '#']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>page-signin-forgot-back</value>
      <webElementGuid>a829bf20-4474-4f5a-86ea-31c8102a1ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>← Kembali</value>
      <webElementGuid>13ad051b-9974-4869-afff-376bd336a39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-t-2 text-muted</value>
      <webElementGuid>f4e3c37d-f1fe-4282-a2a6-76ca7af2cd14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-signin-forgot-back&quot;)</value>
      <webElementGuid>e4f7f765-4bc9-46d8-927c-f6ce4b22acc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>25b7e733-7487-4b94-abf3-0e87529d80e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f7ab2e5b-f70b-43f1-8413-6fd043a24002</webElementGuid>
   </webElementProperties>
</WebElementEntity>
