<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>forgot_password</name>
   <tag></tag>
   <elementGuidId>58da34b8-e533-4ac5-82c1-4a5719769522</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Lupa password?' or . = 'Lupa password?')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>page-signin-forgot-link</value>
      <webElementGuid>c06d423b-da86-4ffe-8157-1e7804f47457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-size-12 text-muted pull-xs-right</value>
      <webElementGuid>9287cb75-7863-44e5-9258-17939f5fd154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lupa password?</value>
      <webElementGuid>c637193c-2afc-41a8-8c57-978ce9e2826a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id{&quot;page-signin-form&quot;)/div[@class=&quot;clearfix&quot;]/a[1]</value>
      <webElementGuid>1acc8b4b-7fb7-49b3-95f0-d1eb8f7412bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0c43f807-20ea-4b83-9d4f-be9fe35a0701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ccc8ea3d-dd90-430c-9412-79c3b7292b18</webElementGuid>
   </webElementProperties>
</WebElementEntity>
