<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp_trx_cash</name>
   <tag></tag>
   <elementGuidId>e6f86c06-58f4-43ec-b6d3-219833053261</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#trx_cash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='trx_cash']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#trx_cash</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4814b9a-bc23-4f27-accf-3559abce8e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bde10808-6939-435c-9adc-492c255daf7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>trx_cash</value>
      <webElementGuid>42bf4294-d5e1-4263-8e1f-85a6b6e766fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d1215446-e397-46b4-ad8a-fb41bdf88e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control currency_rupiah</value>
      <webElementGuid>585a4433-a961-4dbb-842f-0259d3f1c449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trx_cash</value>
      <webElementGuid>8f0af9c9-a174-44e2-a94a-5a8eed68db3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trx_cash&quot;)</value>
      <webElementGuid>2b4cd1d6-2bad-4ffb-abec-4f34d7b0dc4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='trx_cash']</value>
      <webElementGuid>0652f522-ded3-4e57-9ad3-fa38fe6b4c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_form-close-shift']/div[6]/div/div/input</value>
      <webElementGuid>c6d356b3-cf33-4560-8c35-7714c249f861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>d97c4990-1c38-4da7-9174-d61dd32bebf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'trx_cash' and @id = 'trx_cash']</value>
      <webElementGuid>c004bfb3-4e42-443c-aab1-f13a64ad4e39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
